version: '3'
services:
  crdb:
    image: cockroachdb/cockroach:v21.2.5
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure --store=type=mem,size=0.9 --advertise-addr=localhost
#    volumes:
#      - crdb-volume:/cockroach/cockroach-data
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 500M

#volumes:
#  crdb-volume:
